<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Vestigium.Nuget.Publish</RootNamespace>
    <AssemblyName>Vestigium.Nuget.Publish</AssemblyName>
    <ApplicationTitle>Nuget Publish</ApplicationTitle>
    <Company>Wilkinson Business</Company>
    <Authors>Vestigium</Authors>
    <IsPackable>false</IsPackable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
    <PackageReference Include="Vestigium.Themes" Version="1.0.4" />
    <PackageReference Include="Vestigium.Controls" Version="1.0.0" />
  </ItemGroup>
</Project>
